# Generated by Django 5.0.4 on 2024-05-04 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_tag_user_tag'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='tags',
        ),
        migrations.AddField(
            model_name='conversation',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='authentication.tag'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
